apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-spring-boot-v3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker-spring-boot-v3
  template:
    metadata:
      labels:
        app: docker-spring-boot-v3
    spec:
      containers:
        - name: docker-spring-boot-v3
          image: hdchandesh108/docker-spring-boot-v3
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"              
            limits:
              memory: "256Mi"
              cpu: "500m"              
          ports:
            - containerPort: 8083
