apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-spring-boot-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-spring-boot-v3
  template:
    metadata:
      labels:
        app: docker-spring-boot-v3
    spec:
      containers:
      - name: docker-spring-boot-v3
        image: hdchandesh108/docker-spring-boot-v3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
